### ISSUE TITLE
Create an Order

### ISSUE THREAD

**Issue by rohanshrma** [ordersteam/orders#3]
**As a** E-commerce tool user
**I need** to create an order
**So that** it appears in my list of orders

**Assumptions:**
- Order has a unique ID and associated to a customer ID
- Order ID is auto generated and increments for each unique order
- Order has at least 1 item

**Acceptance Criteria:**
```
-When I call `CREATE /order` then a new order should be added to the list of orders
-The newly created Order should have an associated Order ID, Price, Quantity, Item ID, Customer ID, and Date of Order Creation
```

**Comment by sagonzalezc** [comment]
The create order information should add the following information:
Header: 
Customer_ID
Date?
Total?
Status (Open/Fulfilled/Closed)?

Lines: 
Item
Quantity
Price

Date, Total, Status could maybe be pushed for later, as its not MVP (I think)
