### ISSUE TITLE
Get Order details given an Order_ID

### ISSUE THREAD

**Issue by rohanshrma** [ordersteam/orders#5]
**As a** E-commerce user
**I need** to see an order
**So that** I can read the order details

**Assumptions:**
- Order exists in list of orders

**Acceptance Criteria:**
```
Given an `Order_ID`, when I call `GET /Orders/Order_ID` then I should see the details of the order
```

**Comment by sagonzalezc** [comment]
We should be able to see:

MVP:
Customer ID
Date
Status
Total

Additional:
Line Items and their respective information
