### ISSUE TITLE
Update an Order

### ISSUE THREAD

**Issue by rohanshrma** [ordersteam/orders#7]
**As a** E-commerce user
**I need** a way to update my order
**So that** I can change any necessary details of the order (number of items in the order, price of each item or the entire order)

**Assumptions:**
- Order exists with modifiable details

**Acceptance Criteria:**
```
When I call the `/Orders/Update/{ORDER_ID}` I should be able to change the specific fields (e.g., price, quantity)
```

**Comment by sagonzalezc** [comment]
Update orders should include:

Add, Modify or Delete Line Items
Change Quantities for Line Items
Change Price for Line Items

Additional functionalities (not MVP):
Change Date
