### ISSUE TITLE
Modify application to get database credentials

### ISSUE THREAD

**Issue by rohanshrma** [ordersteam/orders#78]
**As a** developer
**I need** database credentials in an environment variable
**So that** my application can run in the cloud

**Assumptions:**
* Database exists
* environment variable exists

**Acceptance Criteria:**
```
Given my database is accounted for in an environment variable
When I run my application in the cloud
Then my application is able to query and update the database properly
```

**Comment by aritraghosh** [comment]
ElephantSQL instance was configured and the same instance was used in the code when the app is deployed in the cloud
