### ISSUE TITLE
Get Orders by Customer

### ISSUE THREAD

**Issue by rohanshrma** [ordersteam/orders#8]
**As a** E-commerce user
**I need** to see orders by customer
**So that** I can query the orders list by customer

**Assumptions:**
- `Customer_ID` exists
- Orders can be queried by `Customer_ID`

**Acceptance Criteria:**
```
When I call `orders/Customer_ID` I get a list of all orders associated with that `Customer_ID`
```

**Comment by aritraghosh** [comment]
We have this as part of  query. Closing this for now
