### ISSUE TITLE
Push application to IBM Cloud

### ISSUE THREAD

**Issue by rohanshrma** [ordersteam/orders#80]
**As a** developer
**I need** to push my application to the IBM Cloud
**So that** it can run on the cloud

**Assumptions:**
* IBM Cloud exists works properly with Cloud Foundry
* Application runs

**Acceptance Criteria:**
```
Given my application is running and I have set up IBM Cloud
When I submit the command ibmcloud cf push
Then my application is pushed to the cloud
```

**Comment by aritraghosh** [comment]
There is no pull request associated with the request. The latest app was deployed to https://nyu-order-service-s21.us-south.cf.appdomain.cloud from my machine.
